#!/usr/bin/env bash
# Script to make Ubuntu container’s Nginx installation listen on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
