#!/usr/bin/env bash
# Bash script that configures an Ubuntu server thus:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.chg
echo "127.0.0.2		localhost" > ~/hosts.chg
echo "8.8.8.8		facebook.com" >> ~/hosts.chg
cp -f ~/hosts.chg /etc/hosts
