#!/usr/bin/env bash
# A Bash script to make Nginx run as nginx user on port 8080
sudo pkill "apache2"
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
